name: MineplexRemake
main: org.mswsplex.mineplex.msws.Mineplex
version: 1.0
description: Mineplex Remake
commands:
   rank:
      usage: /<command> [Set/Get] [Player] [Rank]
      description: foo